---
title: My Jekyll -site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: shivam@tr.com
description: 'This is my test site via CMS

'
baseurl: 
url: http://yourdomain.com
twitter_username: shivam4u2u
github_username: shivammehrotra1987
markdown: kramdown
